<%@ Page Title="" Language="C#" MasterPageFile="~/Site/Site.Master" AutoEventWireup="true" CodeBehind="ClientSheetFact.aspx.cs" Inherits="KMO.ClientSheetFact" %>
<asp:Content ID="HeaderContent" ContentPlaceHolderID="CPH_HEAD" runat="server">
    <script type='text/javascript'>
        function isNumberKey(sender, evt) {
            var txt = sender.value;
            var dotcontainer = txt.split('.');
            var charCode = (evt.which) ? evt.which : event.keyCode;
            if (!(dotcontainer.length == 1 && charCode == 46) && charCode > 31 && (charCode < 48 || charCode > 57))
                return false;

            return true;
        }

        $(document).ready(function () {
            var dp = $('#<%=txtRentStartingDate.ClientID%>');
            dp.datepicker({
                changeMonth: true,
                changeYear: true,
                format: "dd-mm-yyyy",
                language: "tr"
            }).on('changeDate', function (ev) {
                $(this).blur();
                $(this).datepicker('hide');
            });
        });
    </script>
    <style>
        .GridViewStyle td {
            padding: 2px 10px;
        }

        .modal-dialog1{
            position: absolute;
            left: 50%;           
                      
            top: 50%;
            margin-left: 0px;  
            margin-top: -250px;
        } 
    </style>
</asp:Content>
<asp:Content ID="BodyContent" ContentPlaceHolderID="CPH_BODY_CONTENT" runat="server">
    <div class="container">
        <asp:ScriptManager runat="server" ID="ScriptManager1" />

        <div class="col-xs-12 col-sm-12"><h4>Client Fact Sheet</h4></div>

        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">1.0 Tenant</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <asp:Label ID="lblCFSID" runat="server" Visible="false"></asp:Label>                    
                            <div class="col-xs-12 col-sm-1">Name</div>
                            <div class="col-xs-12 col-sm-8" >
                                <asp:TextBox ID="txtCompanyName" runat="server" 
                                    class="form-control input-sm"
                                    placeholder="Company Name" Width="100%"></asp:TextBox>
                            </div>
                            <div class="col-xs-12 col-sm-1">CID</div>
                            <div class="col-xs-12 col-sm-2" ><asp:Label ID="lblCID" runat="server">[Auto Generated by System]</asp:Label></div>
                        </div>
                        <div class="row">&nbsp</div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">Address</div>
                            <div class="col-xs-12 col-sm-11">
                                <asp:TextBox runat="server" ID="txtAddress" class="form-control input-sm"
                                    Rows="3" Width="100%" placeholder="Address" 
                                    MaxLength="100" style="text-align:left;" TextMode="MultiLine" />
                            </div>
                        </div>
                        <div class="row">&nbsp</div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">City</div>
                            <div class="col-xs-12 col-sm-2"><asp:TextBox ID="txtCity" class="form-control input-sm" runat="server"  placeholder="City" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Zip</div>
                            <div class="col-xs-12 col-sm-2"><asp:TextBox ID="txtZIP" class="form-control input-sm" runat="server"  placeholder="ZIP" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Telp</div>
                            <div class="col-xs-12 col-sm-2"><asp:TextBox ID="txtTelp" class="form-control input-sm" runat="server"  placeholder="Telp" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Fax</div>
                            <div class="col-xs-12 col-sm-2"><asp:TextBox ID="txtFax" class="form-control input-sm" runat="server"  placeholder="Fax" Width="100%"></asp:TextBox></div>
                        </div>   
                    </div>
                </div>
            </div>            
        </div>      
        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">2.0 PIC</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">PIC Name</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC1Name" class="form-control input-sm" runat="server"  placeholder="Name" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Position</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC1Position" class="form-control input-sm" runat="server"  placeholder="Position" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Mobile Ph</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC1MobilePh" class="form-control input-sm" runat="server"  placeholder="Mobile Ph" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Email</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC1Email" class="form-control input-sm" runat="server"  placeholder="Email" Width="100%"></asp:TextBox></div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">PIC Name</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC2Name" class="form-control input-sm" runat="server"  placeholder="Name" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Position</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC2Position" class="form-control input-sm" runat="server"  placeholder="Position" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Mobile Ph</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC2MobilePh" class="form-control input-sm" runat="server"  placeholder="Mobile Ph" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Email</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC2Email" class="form-control input-sm" runat="server"  placeholder="Email" Width="100%"></asp:TextBox></div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">PIC Name</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC3Name" class="form-control input-sm" runat="server"  placeholder="Name" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Position</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC3Position" class="form-control input-sm" runat="server"  placeholder="Position" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Mobile Ph</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC3MobilePh" class="form-control input-sm" runat="server"  placeholder="Mobile Ph" Width="100%"></asp:TextBox></div>
                            <div class="col-xs-12 col-sm-1">Email</div>
                            <div class="col-xs-12 col-sm-2" ><asp:TextBox ID="txtPIC3Email" class="form-control input-sm" runat="server"  placeholder="Email" Width="100%"></asp:TextBox></div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">3.0 Line of Business</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">Line of Business</div>
                            <div class="col-xs-12 col-sm-5">
                                <asp:DropDownList ID="cmbLoB" runat="server" class="form-control input-sm">
                                    <asp:ListItem Value=""></asp:ListItem>
                                    <asp:ListItem Value="10">Banking / Finance</asp:ListItem>
                                    <asp:ListItem Value="11">Service/Consultant</asp:ListItem>
                                    <asp:ListItem Value="12">IT Related Business</asp:ListItem>
                                    <asp:ListItem Value="13">Contrator</asp:ListItem>
                                    <asp:ListItem Value="14">Manufacturers</asp:ListItem>
                                    <asp:ListItem Value="15">Foods</asp:ListItem>
                                    <asp:ListItem Value="80">BUMN</asp:ListItem>
                                    <asp:ListItem Value="99">Other</asp:ListItem>
                                </asp:DropDownList>                        
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <asp:TextBox ID="txtLoB" class="form-control input-sm" runat="server" placeholder="Other" Width="100%"></asp:TextBox>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">4.0 Area & Dates</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-3">Required Space Area</div>
                            <div class="col-xs-12 col-sm-1" >
                                <asp:TextBox ID="txtReqSpaceArea" class="form-control input-sm" runat="server" 
                                    placeholder="(M2)" Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>
                            <div class="col-xs-12 col-sm-3">Proposed Suite No</div>
                            <div class="col-xs-12 col-sm-1" >
                                <asp:TextBox ID="txtProposedSuiteNo" class="form-control input-sm" runat="server"  
                                    Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>
                            <div class="col-xs-12 col-sm-3">Area</div>
                            <div class="col-xs-12 col-sm-1" >
                                <asp:TextBox ID="txtArea" class="form-control input-sm" runat="server"  
                                    placeholder="(M2)" Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-3">Rent Starting Date</div>
                            <div id="datetimepicker1" class="col-xs-12 col-sm-3" class="input-append date" >
                                <asp:TextBox ID="txtRentStartingDate" class="form-control input-sm" runat="server" 
                                    placeholder="Rent Starting Date" Width="100%" >                                    
                                </asp:TextBox>
                            </div>
                            <div class="col-xs-12 col-sm-3">Rent Period</div>
                            <div class="col-xs-12 col-sm-3" >
                                <asp:TextBox ID="txtRentPeriod" class="form-control input-sm" runat="server"  
                                    placeholder="Years" Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">5.0 Parking</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-3">Total <b>Reserved</b> Parking, Cars</div>
                            <div class="col-xs-12 col-sm-1" >
                                <asp:TextBox ID="txtTotReservedParkingCars" class="form-control input-sm" 
                                    runat="server" Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>
                            <div class="col-xs-12 col-sm-3">Total Un-<b>Reserved</b> Parking, Cars</div>
                            <div class="col-xs-12 col-sm-1" >
                                <asp:TextBox ID="txtTotUnReservedParkingCars" class="form-control input-sm" 
                                    runat="server" Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>
                            <div class="col-xs-12 col-sm-3">Total Parking, Motorbikes</div>
                            <div class="col-xs-12 col-sm-1" >
                                <asp:TextBox ID="txtTotParkingMotorbikes" class="form-control input-sm" 
                                    runat="server" Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">6.0 Comm.</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-3">Required Telephone Lines</div>
                            <div class="col-xs-12 col-sm-1" >
                                <asp:TextBox ID="txtReqTelpLine" class="form-control input-sm" 
                                    runat="server" Width="100%" OnKeyPress="return isNumberKey(this, event);"></asp:TextBox>
                            </div>

                            <div class="col-xs-12 col-sm-2">Internet Provider</div>
                            <div class="col-xs-12 col-sm-3" >
                                <asp:DropDownList ID="ddlInternetProvider" runat="server" class="form-control input-sm">
                                    <asp:ListItem Value=""></asp:ListItem>
                                    <asp:ListItem Value="10">FirstMedia</asp:ListItem>
                                    <asp:ListItem Value="11">Excelcomindo</asp:ListItem>
                                    <asp:ListItem Value="12">Telkom</asp:ListItem>
                                    <asp:ListItem Value="99">Other</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                            <div class="col-xs-12 col-sm-3">
                                <asp:TextBox ID="txtOtherInternetProvider" class="form-control input-sm" runat="server" placeholder="Other" Width="100%"></asp:TextBox>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">7.0 Refferal</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">Referred by:</div>
                            <div class="col-xs-12 col-sm-1">Name</div>
                            <div class="col-xs-12 col-sm-2" >
                                <asp:TextBox ID="txtRefferedBy1" class="form-control input-sm" 
                                    runat="server" Width="100%"></asp:TextBox>
                            </div>
                            <div class="col-xs-12 col-sm-3" >
                                <asp:DropDownList ID="ddlRefferal" runat="server" class="form-control input-sm">
                                    <asp:ListItem Value=""></asp:ListItem>
                                    <asp:ListItem Value="10">KMO Rental Signage</asp:ListItem>
                                    <asp:ListItem Value="11">KMO Website</asp:ListItem>
                                    <asp:ListItem Value="12">Newspaper ad</asp:ListItem>
                                    <asp:ListItem Value="99">Other</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                            <div class="col-xs-12 col-sm-5">
                                <asp:TextBox ID="txtRefferalOther" class="form-control input-sm" runat="server" placeholder="Other" Width="100%"></asp:TextBox>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-1">&nbsp</div>
                            <div class="col-xs-12 col-sm-1">Company</div>
                            <div class="col-xs-12 col-sm-2" >
                                <asp:TextBox ID="txtRefferedBy2" class="form-control input-sm" 
                                    runat="server" Width="100%"></asp:TextBox>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row col-xs-12 col-sm-12">
            <div class="col-xs-12 col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">8.0 Special Conditions</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12">
                                <asp:TextBox runat="server" ID="txtSpecialConditions" class="form-control input-sm"
                                    Rows="5" Width="100%" placeholder="Special Conditions" 
                                    MaxLength="100" style="text-align:left;" TextMode="MultiLine" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row col-xs-12 col-sm-12">
            <div class="row col-xs-12 col-sm-12" align="right">
                <div class="row">&nbsp</div>
                <asp:Button ID="btnSave" runat="server" Text="Save" CssClass="btn btn-success" />
                <asp:Button ID="btnCancel" runat="server" Text="Cancel" CssClass="btn btn-danger" />
                <div class="row">&nbsp</div>
            </div>
        </div>
    </div>
</asp:Content>
<asp:Content ID="FooterContent" ContentPlaceHolderID="CPH_SCRIPT" runat="server">
</asp:Content>
