//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KMO.WebService_KMO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_list_pengajuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_list_pengajuan_supervisorOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_list_pengajuan_underwritingOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_list_dokumen_pengajuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_data_detail_pengajuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_ddl_list_bankOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_ddl_list_jenis_dokumen_pengajuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_ddl_polis_login_useridOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_userid_infoOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_ddl_list_premium_typeOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_news_typeOperationCompleted;
        
        private System.Threading.SendOrPostCallback validate_userpassOperationCompleted;
        
        private System.Threading.SendOrPostCallback ins_dokumen_pengajuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback updt_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback del_dokumen_pengajuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback ins_pengajuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback upd_pengajuanOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::KMO.Properties.Settings.Default.KMO_WebService_KMO_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_list_pengajuanCompletedEventHandler get_list_pengajuanCompleted;
        
        /// <remarks/>
        public event get_list_pengajuan_supervisorCompletedEventHandler get_list_pengajuan_supervisorCompleted;
        
        /// <remarks/>
        public event get_list_pengajuan_underwritingCompletedEventHandler get_list_pengajuan_underwritingCompleted;
        
        /// <remarks/>
        public event get_list_dokumen_pengajuanCompletedEventHandler get_list_dokumen_pengajuanCompleted;
        
        /// <remarks/>
        public event get_data_detail_pengajuanCompletedEventHandler get_data_detail_pengajuanCompleted;
        
        /// <remarks/>
        public event get_ddl_list_bankCompletedEventHandler get_ddl_list_bankCompleted;
        
        /// <remarks/>
        public event get_ddl_list_jenis_dokumen_pengajuanCompletedEventHandler get_ddl_list_jenis_dokumen_pengajuanCompleted;
        
        /// <remarks/>
        public event get_ddl_polis_login_useridCompletedEventHandler get_ddl_polis_login_useridCompleted;
        
        /// <remarks/>
        public event get_userid_infoCompletedEventHandler get_userid_infoCompleted;
        
        /// <remarks/>
        public event get_ddl_list_premium_typeCompletedEventHandler get_ddl_list_premium_typeCompleted;
        
        /// <remarks/>
        public event get_news_typeCompletedEventHandler get_news_typeCompleted;
        
        /// <remarks/>
        public event validate_userpassCompletedEventHandler validate_userpassCompleted;
        
        /// <remarks/>
        public event ins_dokumen_pengajuanCompletedEventHandler ins_dokumen_pengajuanCompleted;
        
        /// <remarks/>
        public event updt_statusCompletedEventHandler updt_statusCompleted;
        
        /// <remarks/>
        public event del_dokumen_pengajuanCompletedEventHandler del_dokumen_pengajuanCompleted;
        
        /// <remarks/>
        public event ins_pengajuanCompletedEventHandler ins_pengajuanCompleted;
        
        /// <remarks/>
        public event upd_pengajuanCompletedEventHandler upd_pengajuanCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_list_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_list_pengajuan(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH) {
            object[] results = this.Invoke("get_list_pengajuan", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN,
                        NAMA,
                        PERIODE_MASUK_DARI,
                        PERIODE_MASUK_SAMPAI,
                        NO_BATCH});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_list_pengajuanAsync(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH) {
            this.get_list_pengajuanAsync(NO_POLIS, NO_PENGAJUAN, NAMA, PERIODE_MASUK_DARI, PERIODE_MASUK_SAMPAI, NO_BATCH, null);
        }
        
        /// <remarks/>
        public void get_list_pengajuanAsync(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH, object userState) {
            if ((this.get_list_pengajuanOperationCompleted == null)) {
                this.get_list_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_list_pengajuanOperationCompleted);
            }
            this.InvokeAsync("get_list_pengajuan", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN,
                        NAMA,
                        PERIODE_MASUK_DARI,
                        PERIODE_MASUK_SAMPAI,
                        NO_BATCH}, this.get_list_pengajuanOperationCompleted, userState);
        }
        
        private void Onget_list_pengajuanOperationCompleted(object arg) {
            if ((this.get_list_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_list_pengajuanCompleted(this, new get_list_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_list_pengajuan_supervisor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_list_pengajuan_supervisor(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH) {
            object[] results = this.Invoke("get_list_pengajuan_supervisor", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN,
                        NAMA,
                        PERIODE_MASUK_DARI,
                        PERIODE_MASUK_SAMPAI,
                        NO_BATCH});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_list_pengajuan_supervisorAsync(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH) {
            this.get_list_pengajuan_supervisorAsync(NO_POLIS, NO_PENGAJUAN, NAMA, PERIODE_MASUK_DARI, PERIODE_MASUK_SAMPAI, NO_BATCH, null);
        }
        
        /// <remarks/>
        public void get_list_pengajuan_supervisorAsync(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH, object userState) {
            if ((this.get_list_pengajuan_supervisorOperationCompleted == null)) {
                this.get_list_pengajuan_supervisorOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_list_pengajuan_supervisorOperationCompleted);
            }
            this.InvokeAsync("get_list_pengajuan_supervisor", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN,
                        NAMA,
                        PERIODE_MASUK_DARI,
                        PERIODE_MASUK_SAMPAI,
                        NO_BATCH}, this.get_list_pengajuan_supervisorOperationCompleted, userState);
        }
        
        private void Onget_list_pengajuan_supervisorOperationCompleted(object arg) {
            if ((this.get_list_pengajuan_supervisorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_list_pengajuan_supervisorCompleted(this, new get_list_pengajuan_supervisorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_list_pengajuan_underwriting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_list_pengajuan_underwriting(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH) {
            object[] results = this.Invoke("get_list_pengajuan_underwriting", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN,
                        NAMA,
                        PERIODE_MASUK_DARI,
                        PERIODE_MASUK_SAMPAI,
                        NO_BATCH});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_list_pengajuan_underwritingAsync(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH) {
            this.get_list_pengajuan_underwritingAsync(NO_POLIS, NO_PENGAJUAN, NAMA, PERIODE_MASUK_DARI, PERIODE_MASUK_SAMPAI, NO_BATCH, null);
        }
        
        /// <remarks/>
        public void get_list_pengajuan_underwritingAsync(string NO_POLIS, string NO_PENGAJUAN, string NAMA, string PERIODE_MASUK_DARI, string PERIODE_MASUK_SAMPAI, string NO_BATCH, object userState) {
            if ((this.get_list_pengajuan_underwritingOperationCompleted == null)) {
                this.get_list_pengajuan_underwritingOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_list_pengajuan_underwritingOperationCompleted);
            }
            this.InvokeAsync("get_list_pengajuan_underwriting", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN,
                        NAMA,
                        PERIODE_MASUK_DARI,
                        PERIODE_MASUK_SAMPAI,
                        NO_BATCH}, this.get_list_pengajuan_underwritingOperationCompleted, userState);
        }
        
        private void Onget_list_pengajuan_underwritingOperationCompleted(object arg) {
            if ((this.get_list_pengajuan_underwritingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_list_pengajuan_underwritingCompleted(this, new get_list_pengajuan_underwritingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_list_dokumen_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_list_dokumen_pengajuan(string NO_POLIS, string NO_PENGAJUAN) {
            object[] results = this.Invoke("get_list_dokumen_pengajuan", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_list_dokumen_pengajuanAsync(string NO_POLIS, string NO_PENGAJUAN) {
            this.get_list_dokumen_pengajuanAsync(NO_POLIS, NO_PENGAJUAN, null);
        }
        
        /// <remarks/>
        public void get_list_dokumen_pengajuanAsync(string NO_POLIS, string NO_PENGAJUAN, object userState) {
            if ((this.get_list_dokumen_pengajuanOperationCompleted == null)) {
                this.get_list_dokumen_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_list_dokumen_pengajuanOperationCompleted);
            }
            this.InvokeAsync("get_list_dokumen_pengajuan", new object[] {
                        NO_POLIS,
                        NO_PENGAJUAN}, this.get_list_dokumen_pengajuanOperationCompleted, userState);
        }
        
        private void Onget_list_dokumen_pengajuanOperationCompleted(object arg) {
            if ((this.get_list_dokumen_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_list_dokumen_pengajuanCompleted(this, new get_list_dokumen_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_data_detail_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_data_detail_pengajuan(string NO_PENGAJUAN) {
            object[] results = this.Invoke("get_data_detail_pengajuan", new object[] {
                        NO_PENGAJUAN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_data_detail_pengajuanAsync(string NO_PENGAJUAN) {
            this.get_data_detail_pengajuanAsync(NO_PENGAJUAN, null);
        }
        
        /// <remarks/>
        public void get_data_detail_pengajuanAsync(string NO_PENGAJUAN, object userState) {
            if ((this.get_data_detail_pengajuanOperationCompleted == null)) {
                this.get_data_detail_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_data_detail_pengajuanOperationCompleted);
            }
            this.InvokeAsync("get_data_detail_pengajuan", new object[] {
                        NO_PENGAJUAN}, this.get_data_detail_pengajuanOperationCompleted, userState);
        }
        
        private void Onget_data_detail_pengajuanOperationCompleted(object arg) {
            if ((this.get_data_detail_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_data_detail_pengajuanCompleted(this, new get_data_detail_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_ddl_list_bank", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_ddl_list_bank(string NO_POLIS) {
            object[] results = this.Invoke("get_ddl_list_bank", new object[] {
                        NO_POLIS});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_ddl_list_bankAsync(string NO_POLIS) {
            this.get_ddl_list_bankAsync(NO_POLIS, null);
        }
        
        /// <remarks/>
        public void get_ddl_list_bankAsync(string NO_POLIS, object userState) {
            if ((this.get_ddl_list_bankOperationCompleted == null)) {
                this.get_ddl_list_bankOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_ddl_list_bankOperationCompleted);
            }
            this.InvokeAsync("get_ddl_list_bank", new object[] {
                        NO_POLIS}, this.get_ddl_list_bankOperationCompleted, userState);
        }
        
        private void Onget_ddl_list_bankOperationCompleted(object arg) {
            if ((this.get_ddl_list_bankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_ddl_list_bankCompleted(this, new get_ddl_list_bankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_ddl_list_jenis_dokumen_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_ddl_list_jenis_dokumen_pengajuan() {
            object[] results = this.Invoke("get_ddl_list_jenis_dokumen_pengajuan", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_ddl_list_jenis_dokumen_pengajuanAsync() {
            this.get_ddl_list_jenis_dokumen_pengajuanAsync(null);
        }
        
        /// <remarks/>
        public void get_ddl_list_jenis_dokumen_pengajuanAsync(object userState) {
            if ((this.get_ddl_list_jenis_dokumen_pengajuanOperationCompleted == null)) {
                this.get_ddl_list_jenis_dokumen_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_ddl_list_jenis_dokumen_pengajuanOperationCompleted);
            }
            this.InvokeAsync("get_ddl_list_jenis_dokumen_pengajuan", new object[0], this.get_ddl_list_jenis_dokumen_pengajuanOperationCompleted, userState);
        }
        
        private void Onget_ddl_list_jenis_dokumen_pengajuanOperationCompleted(object arg) {
            if ((this.get_ddl_list_jenis_dokumen_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_ddl_list_jenis_dokumen_pengajuanCompleted(this, new get_ddl_list_jenis_dokumen_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_ddl_polis_login_userid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_ddl_polis_login_userid(string username) {
            object[] results = this.Invoke("get_ddl_polis_login_userid", new object[] {
                        username});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_ddl_polis_login_useridAsync(string username) {
            this.get_ddl_polis_login_useridAsync(username, null);
        }
        
        /// <remarks/>
        public void get_ddl_polis_login_useridAsync(string username, object userState) {
            if ((this.get_ddl_polis_login_useridOperationCompleted == null)) {
                this.get_ddl_polis_login_useridOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_ddl_polis_login_useridOperationCompleted);
            }
            this.InvokeAsync("get_ddl_polis_login_userid", new object[] {
                        username}, this.get_ddl_polis_login_useridOperationCompleted, userState);
        }
        
        private void Onget_ddl_polis_login_useridOperationCompleted(object arg) {
            if ((this.get_ddl_polis_login_useridCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_ddl_polis_login_useridCompleted(this, new get_ddl_polis_login_useridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_userid_info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_userid_info(string username, string password) {
            object[] results = this.Invoke("get_userid_info", new object[] {
                        username,
                        password});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_userid_infoAsync(string username, string password) {
            this.get_userid_infoAsync(username, password, null);
        }
        
        /// <remarks/>
        public void get_userid_infoAsync(string username, string password, object userState) {
            if ((this.get_userid_infoOperationCompleted == null)) {
                this.get_userid_infoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_userid_infoOperationCompleted);
            }
            this.InvokeAsync("get_userid_info", new object[] {
                        username,
                        password}, this.get_userid_infoOperationCompleted, userState);
        }
        
        private void Onget_userid_infoOperationCompleted(object arg) {
            if ((this.get_userid_infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_userid_infoCompleted(this, new get_userid_infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_ddl_list_premium_type", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_ddl_list_premium_type(string NO_POLIS) {
            object[] results = this.Invoke("get_ddl_list_premium_type", new object[] {
                        NO_POLIS});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_ddl_list_premium_typeAsync(string NO_POLIS) {
            this.get_ddl_list_premium_typeAsync(NO_POLIS, null);
        }
        
        /// <remarks/>
        public void get_ddl_list_premium_typeAsync(string NO_POLIS, object userState) {
            if ((this.get_ddl_list_premium_typeOperationCompleted == null)) {
                this.get_ddl_list_premium_typeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_ddl_list_premium_typeOperationCompleted);
            }
            this.InvokeAsync("get_ddl_list_premium_type", new object[] {
                        NO_POLIS}, this.get_ddl_list_premium_typeOperationCompleted, userState);
        }
        
        private void Onget_ddl_list_premium_typeOperationCompleted(object arg) {
            if ((this.get_ddl_list_premium_typeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_ddl_list_premium_typeCompleted(this, new get_ddl_list_premium_typeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_news_type", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_news_type(int NEWS_TYPE) {
            object[] results = this.Invoke("get_news_type", new object[] {
                        NEWS_TYPE});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_news_typeAsync(int NEWS_TYPE) {
            this.get_news_typeAsync(NEWS_TYPE, null);
        }
        
        /// <remarks/>
        public void get_news_typeAsync(int NEWS_TYPE, object userState) {
            if ((this.get_news_typeOperationCompleted == null)) {
                this.get_news_typeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_news_typeOperationCompleted);
            }
            this.InvokeAsync("get_news_type", new object[] {
                        NEWS_TYPE}, this.get_news_typeOperationCompleted, userState);
        }
        
        private void Onget_news_typeOperationCompleted(object arg) {
            if ((this.get_news_typeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_news_typeCompleted(this, new get_news_typeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validate_userpass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validate_userpass(string user, string pass) {
            object[] results = this.Invoke("validate_userpass", new object[] {
                        user,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validate_userpassAsync(string user, string pass) {
            this.validate_userpassAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void validate_userpassAsync(string user, string pass, object userState) {
            if ((this.validate_userpassOperationCompleted == null)) {
                this.validate_userpassOperationCompleted = new System.Threading.SendOrPostCallback(this.Onvalidate_userpassOperationCompleted);
            }
            this.InvokeAsync("validate_userpass", new object[] {
                        user,
                        pass}, this.validate_userpassOperationCompleted, userState);
        }
        
        private void Onvalidate_userpassOperationCompleted(object arg) {
            if ((this.validate_userpassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validate_userpassCompleted(this, new validate_userpassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ins_dokumen_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ins_dokumen_pengajuan(string GENERATE_ID, int DOC_TYPE_ID, string DOC_NAME_ORI, string DOC_NAME_MOD, string DOC_LOC, string ENTRY_USER) {
            object[] results = this.Invoke("ins_dokumen_pengajuan", new object[] {
                        GENERATE_ID,
                        DOC_TYPE_ID,
                        DOC_NAME_ORI,
                        DOC_NAME_MOD,
                        DOC_LOC,
                        ENTRY_USER});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ins_dokumen_pengajuanAsync(string GENERATE_ID, int DOC_TYPE_ID, string DOC_NAME_ORI, string DOC_NAME_MOD, string DOC_LOC, string ENTRY_USER) {
            this.ins_dokumen_pengajuanAsync(GENERATE_ID, DOC_TYPE_ID, DOC_NAME_ORI, DOC_NAME_MOD, DOC_LOC, ENTRY_USER, null);
        }
        
        /// <remarks/>
        public void ins_dokumen_pengajuanAsync(string GENERATE_ID, int DOC_TYPE_ID, string DOC_NAME_ORI, string DOC_NAME_MOD, string DOC_LOC, string ENTRY_USER, object userState) {
            if ((this.ins_dokumen_pengajuanOperationCompleted == null)) {
                this.ins_dokumen_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onins_dokumen_pengajuanOperationCompleted);
            }
            this.InvokeAsync("ins_dokumen_pengajuan", new object[] {
                        GENERATE_ID,
                        DOC_TYPE_ID,
                        DOC_NAME_ORI,
                        DOC_NAME_MOD,
                        DOC_LOC,
                        ENTRY_USER}, this.ins_dokumen_pengajuanOperationCompleted, userState);
        }
        
        private void Onins_dokumen_pengajuanOperationCompleted(object arg) {
            if ((this.ins_dokumen_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ins_dokumen_pengajuanCompleted(this, new ins_dokumen_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updt_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updt_status(string GENERATE_ID, int prev_STATUS_ID, int next_STATUS_ID, int MODE) {
            object[] results = this.Invoke("updt_status", new object[] {
                        GENERATE_ID,
                        prev_STATUS_ID,
                        next_STATUS_ID,
                        MODE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updt_statusAsync(string GENERATE_ID, int prev_STATUS_ID, int next_STATUS_ID, int MODE) {
            this.updt_statusAsync(GENERATE_ID, prev_STATUS_ID, next_STATUS_ID, MODE, null);
        }
        
        /// <remarks/>
        public void updt_statusAsync(string GENERATE_ID, int prev_STATUS_ID, int next_STATUS_ID, int MODE, object userState) {
            if ((this.updt_statusOperationCompleted == null)) {
                this.updt_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdt_statusOperationCompleted);
            }
            this.InvokeAsync("updt_status", new object[] {
                        GENERATE_ID,
                        prev_STATUS_ID,
                        next_STATUS_ID,
                        MODE}, this.updt_statusOperationCompleted, userState);
        }
        
        private void Onupdt_statusOperationCompleted(object arg) {
            if ((this.updt_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updt_statusCompleted(this, new updt_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/del_dokumen_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string del_dokumen_pengajuan(string NO_PENGAJUAN, string NAMA_DOKUMEN) {
            object[] results = this.Invoke("del_dokumen_pengajuan", new object[] {
                        NO_PENGAJUAN,
                        NAMA_DOKUMEN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void del_dokumen_pengajuanAsync(string NO_PENGAJUAN, string NAMA_DOKUMEN) {
            this.del_dokumen_pengajuanAsync(NO_PENGAJUAN, NAMA_DOKUMEN, null);
        }
        
        /// <remarks/>
        public void del_dokumen_pengajuanAsync(string NO_PENGAJUAN, string NAMA_DOKUMEN, object userState) {
            if ((this.del_dokumen_pengajuanOperationCompleted == null)) {
                this.del_dokumen_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondel_dokumen_pengajuanOperationCompleted);
            }
            this.InvokeAsync("del_dokumen_pengajuan", new object[] {
                        NO_PENGAJUAN,
                        NAMA_DOKUMEN}, this.del_dokumen_pengajuanOperationCompleted, userState);
        }
        
        private void Ondel_dokumen_pengajuanOperationCompleted(object arg) {
            if ((this.del_dokumen_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.del_dokumen_pengajuanCompleted(this, new del_dokumen_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ins_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ins_pengajuan(
                    int BRANCH_ID, 
                    string BANK_ID, 
                    string NO_REK, 
                    string NAMA_PEMILIK_REK, 
                    decimal PENGHASILAN_PER_TAHUN, 
                    string SUMBER_PENDANAAN, 
                    string TUJUAN_PENGAJUAN_MENJADI_PESERTA, 
                    decimal UANG_PERTANGGUNGAN, 
                    int PREMI_SEKALIGUS, 
                    string TINGKAT_BUNGA_PER_TAHUN, 
                    string MULAI_PERTANGGUNGAN, 
                    string AKHIR_PERTANGGUNGAN, 
                    string NAMA_PENERIMA_MANFAAT_ASURANSI, 
                    string NO_POLIS_1, 
                    decimal JUMLAH_1, 
                    string NAMA_PERUSAHAAN_1, 
                    string NO_POLIS_2, 
                    decimal JUMLAH_2, 
                    string NAMA_PERUSAHAAN_2, 
                    string DEBITUR_NAMA, 
                    string DEBITUR_JENIS_KELAMIN, 
                    string DEBITUR_NIK, 
                    string DEBITUR_LAHIR_TEMPAT, 
                    string DEBITUR_LAHIR_TANGGAL, 
                    string DEBITUR_EMAIL, 
                    string DEBITUR_PEKERJAAN, 
                    string PESERTA_ALAMAT, 
                    string PESERTA_KOTA, 
                    string PESERTA_KODE_POS, 
                    string PESERTA_TELP, 
                    string PESERTA_FAX, 
                    string KORESPONDENSI_ALAMAT, 
                    string KORESPONDENSI_KOTA, 
                    string KORESPONDENSI_KODE_POS, 
                    string KORESPONDENSI_TELP, 
                    string KORESPONDENSI_FAX, 
                    int Q1_BADAN_BERAT, 
                    int Q1_BADAN_TINGGI, 
                    int Q2_PERAWATAN_OPSI, 
                    string Q2_PERAWATAN_DESC, 
                    int Q3_DIRAWAT_OPSI, 
                    string Q3_DIRAWAT_DESC, 
                    int Q4_MENDERITA_OPSI, 
                    string Q4_MENDERITA_DESC, 
                    string SES_NO_POLIS) {
            object[] results = this.Invoke("ins_pengajuan", new object[] {
                        BRANCH_ID,
                        BANK_ID,
                        NO_REK,
                        NAMA_PEMILIK_REK,
                        PENGHASILAN_PER_TAHUN,
                        SUMBER_PENDANAAN,
                        TUJUAN_PENGAJUAN_MENJADI_PESERTA,
                        UANG_PERTANGGUNGAN,
                        PREMI_SEKALIGUS,
                        TINGKAT_BUNGA_PER_TAHUN,
                        MULAI_PERTANGGUNGAN,
                        AKHIR_PERTANGGUNGAN,
                        NAMA_PENERIMA_MANFAAT_ASURANSI,
                        NO_POLIS_1,
                        JUMLAH_1,
                        NAMA_PERUSAHAAN_1,
                        NO_POLIS_2,
                        JUMLAH_2,
                        NAMA_PERUSAHAAN_2,
                        DEBITUR_NAMA,
                        DEBITUR_JENIS_KELAMIN,
                        DEBITUR_NIK,
                        DEBITUR_LAHIR_TEMPAT,
                        DEBITUR_LAHIR_TANGGAL,
                        DEBITUR_EMAIL,
                        DEBITUR_PEKERJAAN,
                        PESERTA_ALAMAT,
                        PESERTA_KOTA,
                        PESERTA_KODE_POS,
                        PESERTA_TELP,
                        PESERTA_FAX,
                        KORESPONDENSI_ALAMAT,
                        KORESPONDENSI_KOTA,
                        KORESPONDENSI_KODE_POS,
                        KORESPONDENSI_TELP,
                        KORESPONDENSI_FAX,
                        Q1_BADAN_BERAT,
                        Q1_BADAN_TINGGI,
                        Q2_PERAWATAN_OPSI,
                        Q2_PERAWATAN_DESC,
                        Q3_DIRAWAT_OPSI,
                        Q3_DIRAWAT_DESC,
                        Q4_MENDERITA_OPSI,
                        Q4_MENDERITA_DESC,
                        SES_NO_POLIS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ins_pengajuanAsync(
                    int BRANCH_ID, 
                    string BANK_ID, 
                    string NO_REK, 
                    string NAMA_PEMILIK_REK, 
                    decimal PENGHASILAN_PER_TAHUN, 
                    string SUMBER_PENDANAAN, 
                    string TUJUAN_PENGAJUAN_MENJADI_PESERTA, 
                    decimal UANG_PERTANGGUNGAN, 
                    int PREMI_SEKALIGUS, 
                    string TINGKAT_BUNGA_PER_TAHUN, 
                    string MULAI_PERTANGGUNGAN, 
                    string AKHIR_PERTANGGUNGAN, 
                    string NAMA_PENERIMA_MANFAAT_ASURANSI, 
                    string NO_POLIS_1, 
                    decimal JUMLAH_1, 
                    string NAMA_PERUSAHAAN_1, 
                    string NO_POLIS_2, 
                    decimal JUMLAH_2, 
                    string NAMA_PERUSAHAAN_2, 
                    string DEBITUR_NAMA, 
                    string DEBITUR_JENIS_KELAMIN, 
                    string DEBITUR_NIK, 
                    string DEBITUR_LAHIR_TEMPAT, 
                    string DEBITUR_LAHIR_TANGGAL, 
                    string DEBITUR_EMAIL, 
                    string DEBITUR_PEKERJAAN, 
                    string PESERTA_ALAMAT, 
                    string PESERTA_KOTA, 
                    string PESERTA_KODE_POS, 
                    string PESERTA_TELP, 
                    string PESERTA_FAX, 
                    string KORESPONDENSI_ALAMAT, 
                    string KORESPONDENSI_KOTA, 
                    string KORESPONDENSI_KODE_POS, 
                    string KORESPONDENSI_TELP, 
                    string KORESPONDENSI_FAX, 
                    int Q1_BADAN_BERAT, 
                    int Q1_BADAN_TINGGI, 
                    int Q2_PERAWATAN_OPSI, 
                    string Q2_PERAWATAN_DESC, 
                    int Q3_DIRAWAT_OPSI, 
                    string Q3_DIRAWAT_DESC, 
                    int Q4_MENDERITA_OPSI, 
                    string Q4_MENDERITA_DESC, 
                    string SES_NO_POLIS) {
            this.ins_pengajuanAsync(BRANCH_ID, BANK_ID, NO_REK, NAMA_PEMILIK_REK, PENGHASILAN_PER_TAHUN, SUMBER_PENDANAAN, TUJUAN_PENGAJUAN_MENJADI_PESERTA, UANG_PERTANGGUNGAN, PREMI_SEKALIGUS, TINGKAT_BUNGA_PER_TAHUN, MULAI_PERTANGGUNGAN, AKHIR_PERTANGGUNGAN, NAMA_PENERIMA_MANFAAT_ASURANSI, NO_POLIS_1, JUMLAH_1, NAMA_PERUSAHAAN_1, NO_POLIS_2, JUMLAH_2, NAMA_PERUSAHAAN_2, DEBITUR_NAMA, DEBITUR_JENIS_KELAMIN, DEBITUR_NIK, DEBITUR_LAHIR_TEMPAT, DEBITUR_LAHIR_TANGGAL, DEBITUR_EMAIL, DEBITUR_PEKERJAAN, PESERTA_ALAMAT, PESERTA_KOTA, PESERTA_KODE_POS, PESERTA_TELP, PESERTA_FAX, KORESPONDENSI_ALAMAT, KORESPONDENSI_KOTA, KORESPONDENSI_KODE_POS, KORESPONDENSI_TELP, KORESPONDENSI_FAX, Q1_BADAN_BERAT, Q1_BADAN_TINGGI, Q2_PERAWATAN_OPSI, Q2_PERAWATAN_DESC, Q3_DIRAWAT_OPSI, Q3_DIRAWAT_DESC, Q4_MENDERITA_OPSI, Q4_MENDERITA_DESC, SES_NO_POLIS, null);
        }
        
        /// <remarks/>
        public void ins_pengajuanAsync(
                    int BRANCH_ID, 
                    string BANK_ID, 
                    string NO_REK, 
                    string NAMA_PEMILIK_REK, 
                    decimal PENGHASILAN_PER_TAHUN, 
                    string SUMBER_PENDANAAN, 
                    string TUJUAN_PENGAJUAN_MENJADI_PESERTA, 
                    decimal UANG_PERTANGGUNGAN, 
                    int PREMI_SEKALIGUS, 
                    string TINGKAT_BUNGA_PER_TAHUN, 
                    string MULAI_PERTANGGUNGAN, 
                    string AKHIR_PERTANGGUNGAN, 
                    string NAMA_PENERIMA_MANFAAT_ASURANSI, 
                    string NO_POLIS_1, 
                    decimal JUMLAH_1, 
                    string NAMA_PERUSAHAAN_1, 
                    string NO_POLIS_2, 
                    decimal JUMLAH_2, 
                    string NAMA_PERUSAHAAN_2, 
                    string DEBITUR_NAMA, 
                    string DEBITUR_JENIS_KELAMIN, 
                    string DEBITUR_NIK, 
                    string DEBITUR_LAHIR_TEMPAT, 
                    string DEBITUR_LAHIR_TANGGAL, 
                    string DEBITUR_EMAIL, 
                    string DEBITUR_PEKERJAAN, 
                    string PESERTA_ALAMAT, 
                    string PESERTA_KOTA, 
                    string PESERTA_KODE_POS, 
                    string PESERTA_TELP, 
                    string PESERTA_FAX, 
                    string KORESPONDENSI_ALAMAT, 
                    string KORESPONDENSI_KOTA, 
                    string KORESPONDENSI_KODE_POS, 
                    string KORESPONDENSI_TELP, 
                    string KORESPONDENSI_FAX, 
                    int Q1_BADAN_BERAT, 
                    int Q1_BADAN_TINGGI, 
                    int Q2_PERAWATAN_OPSI, 
                    string Q2_PERAWATAN_DESC, 
                    int Q3_DIRAWAT_OPSI, 
                    string Q3_DIRAWAT_DESC, 
                    int Q4_MENDERITA_OPSI, 
                    string Q4_MENDERITA_DESC, 
                    string SES_NO_POLIS, 
                    object userState) {
            if ((this.ins_pengajuanOperationCompleted == null)) {
                this.ins_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onins_pengajuanOperationCompleted);
            }
            this.InvokeAsync("ins_pengajuan", new object[] {
                        BRANCH_ID,
                        BANK_ID,
                        NO_REK,
                        NAMA_PEMILIK_REK,
                        PENGHASILAN_PER_TAHUN,
                        SUMBER_PENDANAAN,
                        TUJUAN_PENGAJUAN_MENJADI_PESERTA,
                        UANG_PERTANGGUNGAN,
                        PREMI_SEKALIGUS,
                        TINGKAT_BUNGA_PER_TAHUN,
                        MULAI_PERTANGGUNGAN,
                        AKHIR_PERTANGGUNGAN,
                        NAMA_PENERIMA_MANFAAT_ASURANSI,
                        NO_POLIS_1,
                        JUMLAH_1,
                        NAMA_PERUSAHAAN_1,
                        NO_POLIS_2,
                        JUMLAH_2,
                        NAMA_PERUSAHAAN_2,
                        DEBITUR_NAMA,
                        DEBITUR_JENIS_KELAMIN,
                        DEBITUR_NIK,
                        DEBITUR_LAHIR_TEMPAT,
                        DEBITUR_LAHIR_TANGGAL,
                        DEBITUR_EMAIL,
                        DEBITUR_PEKERJAAN,
                        PESERTA_ALAMAT,
                        PESERTA_KOTA,
                        PESERTA_KODE_POS,
                        PESERTA_TELP,
                        PESERTA_FAX,
                        KORESPONDENSI_ALAMAT,
                        KORESPONDENSI_KOTA,
                        KORESPONDENSI_KODE_POS,
                        KORESPONDENSI_TELP,
                        KORESPONDENSI_FAX,
                        Q1_BADAN_BERAT,
                        Q1_BADAN_TINGGI,
                        Q2_PERAWATAN_OPSI,
                        Q2_PERAWATAN_DESC,
                        Q3_DIRAWAT_OPSI,
                        Q3_DIRAWAT_DESC,
                        Q4_MENDERITA_OPSI,
                        Q4_MENDERITA_DESC,
                        SES_NO_POLIS}, this.ins_pengajuanOperationCompleted, userState);
        }
        
        private void Onins_pengajuanOperationCompleted(object arg) {
            if ((this.ins_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ins_pengajuanCompleted(this, new ins_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/upd_pengajuan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string upd_pengajuan(
                    int BRANCH_ID, 
                    string BANK_ID, 
                    string NO_REK, 
                    string NAMA_PEMILIK_REK, 
                    decimal PENGHASILAN_PER_TAHUN, 
                    string SUMBER_PENDANAAN, 
                    string TUJUAN_PENGAJUAN_MENJADI_PESERTA, 
                    decimal UANG_PERTANGGUNGAN, 
                    int PREMI_SEKALIGUS, 
                    string TINGKAT_BUNGA_PER_TAHUN, 
                    string MULAI_PERTANGGUNGAN, 
                    string AKHIR_PERTANGGUNGAN, 
                    string NAMA_PENERIMA_MANFAAT_ASURANSI, 
                    string NO_POLIS_1, 
                    decimal JUMLAH_1, 
                    string NAMA_PERUSAHAAN_1, 
                    string NO_POLIS_2, 
                    decimal JUMLAH_2, 
                    string NAMA_PERUSAHAAN_2, 
                    string DEBITUR_NAMA, 
                    string DEBITUR_JENIS_KELAMIN, 
                    string DEBITUR_NIK, 
                    string DEBITUR_LAHIR_TEMPAT, 
                    string DEBITUR_LAHIR_TANGGAL, 
                    string DEBITUR_EMAIL, 
                    string DEBITUR_PEKERJAAN, 
                    string PESERTA_ALAMAT, 
                    string PESERTA_KOTA, 
                    string PESERTA_KODE_POS, 
                    string PESERTA_TELP, 
                    string PESERTA_FAX, 
                    string KORESPONDENSI_ALAMAT, 
                    string KORESPONDENSI_KOTA, 
                    string KORESPONDENSI_KODE_POS, 
                    string KORESPONDENSI_TELP, 
                    string KORESPONDENSI_FAX, 
                    int Q1_BADAN_BERAT, 
                    int Q1_BADAN_TINGGI, 
                    int Q2_PERAWATAN_OPSI, 
                    string Q2_PERAWATAN_DESC, 
                    int Q3_DIRAWAT_OPSI, 
                    string Q3_DIRAWAT_DESC, 
                    int Q4_MENDERITA_OPSI, 
                    string Q4_MENDERITA_DESC, 
                    string SES_NO_POLIS, 
                    string NO_REGISTRATION) {
            object[] results = this.Invoke("upd_pengajuan", new object[] {
                        BRANCH_ID,
                        BANK_ID,
                        NO_REK,
                        NAMA_PEMILIK_REK,
                        PENGHASILAN_PER_TAHUN,
                        SUMBER_PENDANAAN,
                        TUJUAN_PENGAJUAN_MENJADI_PESERTA,
                        UANG_PERTANGGUNGAN,
                        PREMI_SEKALIGUS,
                        TINGKAT_BUNGA_PER_TAHUN,
                        MULAI_PERTANGGUNGAN,
                        AKHIR_PERTANGGUNGAN,
                        NAMA_PENERIMA_MANFAAT_ASURANSI,
                        NO_POLIS_1,
                        JUMLAH_1,
                        NAMA_PERUSAHAAN_1,
                        NO_POLIS_2,
                        JUMLAH_2,
                        NAMA_PERUSAHAAN_2,
                        DEBITUR_NAMA,
                        DEBITUR_JENIS_KELAMIN,
                        DEBITUR_NIK,
                        DEBITUR_LAHIR_TEMPAT,
                        DEBITUR_LAHIR_TANGGAL,
                        DEBITUR_EMAIL,
                        DEBITUR_PEKERJAAN,
                        PESERTA_ALAMAT,
                        PESERTA_KOTA,
                        PESERTA_KODE_POS,
                        PESERTA_TELP,
                        PESERTA_FAX,
                        KORESPONDENSI_ALAMAT,
                        KORESPONDENSI_KOTA,
                        KORESPONDENSI_KODE_POS,
                        KORESPONDENSI_TELP,
                        KORESPONDENSI_FAX,
                        Q1_BADAN_BERAT,
                        Q1_BADAN_TINGGI,
                        Q2_PERAWATAN_OPSI,
                        Q2_PERAWATAN_DESC,
                        Q3_DIRAWAT_OPSI,
                        Q3_DIRAWAT_DESC,
                        Q4_MENDERITA_OPSI,
                        Q4_MENDERITA_DESC,
                        SES_NO_POLIS,
                        NO_REGISTRATION});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void upd_pengajuanAsync(
                    int BRANCH_ID, 
                    string BANK_ID, 
                    string NO_REK, 
                    string NAMA_PEMILIK_REK, 
                    decimal PENGHASILAN_PER_TAHUN, 
                    string SUMBER_PENDANAAN, 
                    string TUJUAN_PENGAJUAN_MENJADI_PESERTA, 
                    decimal UANG_PERTANGGUNGAN, 
                    int PREMI_SEKALIGUS, 
                    string TINGKAT_BUNGA_PER_TAHUN, 
                    string MULAI_PERTANGGUNGAN, 
                    string AKHIR_PERTANGGUNGAN, 
                    string NAMA_PENERIMA_MANFAAT_ASURANSI, 
                    string NO_POLIS_1, 
                    decimal JUMLAH_1, 
                    string NAMA_PERUSAHAAN_1, 
                    string NO_POLIS_2, 
                    decimal JUMLAH_2, 
                    string NAMA_PERUSAHAAN_2, 
                    string DEBITUR_NAMA, 
                    string DEBITUR_JENIS_KELAMIN, 
                    string DEBITUR_NIK, 
                    string DEBITUR_LAHIR_TEMPAT, 
                    string DEBITUR_LAHIR_TANGGAL, 
                    string DEBITUR_EMAIL, 
                    string DEBITUR_PEKERJAAN, 
                    string PESERTA_ALAMAT, 
                    string PESERTA_KOTA, 
                    string PESERTA_KODE_POS, 
                    string PESERTA_TELP, 
                    string PESERTA_FAX, 
                    string KORESPONDENSI_ALAMAT, 
                    string KORESPONDENSI_KOTA, 
                    string KORESPONDENSI_KODE_POS, 
                    string KORESPONDENSI_TELP, 
                    string KORESPONDENSI_FAX, 
                    int Q1_BADAN_BERAT, 
                    int Q1_BADAN_TINGGI, 
                    int Q2_PERAWATAN_OPSI, 
                    string Q2_PERAWATAN_DESC, 
                    int Q3_DIRAWAT_OPSI, 
                    string Q3_DIRAWAT_DESC, 
                    int Q4_MENDERITA_OPSI, 
                    string Q4_MENDERITA_DESC, 
                    string SES_NO_POLIS, 
                    string NO_REGISTRATION) {
            this.upd_pengajuanAsync(BRANCH_ID, BANK_ID, NO_REK, NAMA_PEMILIK_REK, PENGHASILAN_PER_TAHUN, SUMBER_PENDANAAN, TUJUAN_PENGAJUAN_MENJADI_PESERTA, UANG_PERTANGGUNGAN, PREMI_SEKALIGUS, TINGKAT_BUNGA_PER_TAHUN, MULAI_PERTANGGUNGAN, AKHIR_PERTANGGUNGAN, NAMA_PENERIMA_MANFAAT_ASURANSI, NO_POLIS_1, JUMLAH_1, NAMA_PERUSAHAAN_1, NO_POLIS_2, JUMLAH_2, NAMA_PERUSAHAAN_2, DEBITUR_NAMA, DEBITUR_JENIS_KELAMIN, DEBITUR_NIK, DEBITUR_LAHIR_TEMPAT, DEBITUR_LAHIR_TANGGAL, DEBITUR_EMAIL, DEBITUR_PEKERJAAN, PESERTA_ALAMAT, PESERTA_KOTA, PESERTA_KODE_POS, PESERTA_TELP, PESERTA_FAX, KORESPONDENSI_ALAMAT, KORESPONDENSI_KOTA, KORESPONDENSI_KODE_POS, KORESPONDENSI_TELP, KORESPONDENSI_FAX, Q1_BADAN_BERAT, Q1_BADAN_TINGGI, Q2_PERAWATAN_OPSI, Q2_PERAWATAN_DESC, Q3_DIRAWAT_OPSI, Q3_DIRAWAT_DESC, Q4_MENDERITA_OPSI, Q4_MENDERITA_DESC, SES_NO_POLIS, NO_REGISTRATION, null);
        }
        
        /// <remarks/>
        public void upd_pengajuanAsync(
                    int BRANCH_ID, 
                    string BANK_ID, 
                    string NO_REK, 
                    string NAMA_PEMILIK_REK, 
                    decimal PENGHASILAN_PER_TAHUN, 
                    string SUMBER_PENDANAAN, 
                    string TUJUAN_PENGAJUAN_MENJADI_PESERTA, 
                    decimal UANG_PERTANGGUNGAN, 
                    int PREMI_SEKALIGUS, 
                    string TINGKAT_BUNGA_PER_TAHUN, 
                    string MULAI_PERTANGGUNGAN, 
                    string AKHIR_PERTANGGUNGAN, 
                    string NAMA_PENERIMA_MANFAAT_ASURANSI, 
                    string NO_POLIS_1, 
                    decimal JUMLAH_1, 
                    string NAMA_PERUSAHAAN_1, 
                    string NO_POLIS_2, 
                    decimal JUMLAH_2, 
                    string NAMA_PERUSAHAAN_2, 
                    string DEBITUR_NAMA, 
                    string DEBITUR_JENIS_KELAMIN, 
                    string DEBITUR_NIK, 
                    string DEBITUR_LAHIR_TEMPAT, 
                    string DEBITUR_LAHIR_TANGGAL, 
                    string DEBITUR_EMAIL, 
                    string DEBITUR_PEKERJAAN, 
                    string PESERTA_ALAMAT, 
                    string PESERTA_KOTA, 
                    string PESERTA_KODE_POS, 
                    string PESERTA_TELP, 
                    string PESERTA_FAX, 
                    string KORESPONDENSI_ALAMAT, 
                    string KORESPONDENSI_KOTA, 
                    string KORESPONDENSI_KODE_POS, 
                    string KORESPONDENSI_TELP, 
                    string KORESPONDENSI_FAX, 
                    int Q1_BADAN_BERAT, 
                    int Q1_BADAN_TINGGI, 
                    int Q2_PERAWATAN_OPSI, 
                    string Q2_PERAWATAN_DESC, 
                    int Q3_DIRAWAT_OPSI, 
                    string Q3_DIRAWAT_DESC, 
                    int Q4_MENDERITA_OPSI, 
                    string Q4_MENDERITA_DESC, 
                    string SES_NO_POLIS, 
                    string NO_REGISTRATION, 
                    object userState) {
            if ((this.upd_pengajuanOperationCompleted == null)) {
                this.upd_pengajuanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupd_pengajuanOperationCompleted);
            }
            this.InvokeAsync("upd_pengajuan", new object[] {
                        BRANCH_ID,
                        BANK_ID,
                        NO_REK,
                        NAMA_PEMILIK_REK,
                        PENGHASILAN_PER_TAHUN,
                        SUMBER_PENDANAAN,
                        TUJUAN_PENGAJUAN_MENJADI_PESERTA,
                        UANG_PERTANGGUNGAN,
                        PREMI_SEKALIGUS,
                        TINGKAT_BUNGA_PER_TAHUN,
                        MULAI_PERTANGGUNGAN,
                        AKHIR_PERTANGGUNGAN,
                        NAMA_PENERIMA_MANFAAT_ASURANSI,
                        NO_POLIS_1,
                        JUMLAH_1,
                        NAMA_PERUSAHAAN_1,
                        NO_POLIS_2,
                        JUMLAH_2,
                        NAMA_PERUSAHAAN_2,
                        DEBITUR_NAMA,
                        DEBITUR_JENIS_KELAMIN,
                        DEBITUR_NIK,
                        DEBITUR_LAHIR_TEMPAT,
                        DEBITUR_LAHIR_TANGGAL,
                        DEBITUR_EMAIL,
                        DEBITUR_PEKERJAAN,
                        PESERTA_ALAMAT,
                        PESERTA_KOTA,
                        PESERTA_KODE_POS,
                        PESERTA_TELP,
                        PESERTA_FAX,
                        KORESPONDENSI_ALAMAT,
                        KORESPONDENSI_KOTA,
                        KORESPONDENSI_KODE_POS,
                        KORESPONDENSI_TELP,
                        KORESPONDENSI_FAX,
                        Q1_BADAN_BERAT,
                        Q1_BADAN_TINGGI,
                        Q2_PERAWATAN_OPSI,
                        Q2_PERAWATAN_DESC,
                        Q3_DIRAWAT_OPSI,
                        Q3_DIRAWAT_DESC,
                        Q4_MENDERITA_OPSI,
                        Q4_MENDERITA_DESC,
                        SES_NO_POLIS,
                        NO_REGISTRATION}, this.upd_pengajuanOperationCompleted, userState);
        }
        
        private void Onupd_pengajuanOperationCompleted(object arg) {
            if ((this.upd_pengajuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.upd_pengajuanCompleted(this, new upd_pengajuanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_list_pengajuanCompletedEventHandler(object sender, get_list_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_list_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_list_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_list_pengajuan_supervisorCompletedEventHandler(object sender, get_list_pengajuan_supervisorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_list_pengajuan_supervisorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_list_pengajuan_supervisorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_list_pengajuan_underwritingCompletedEventHandler(object sender, get_list_pengajuan_underwritingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_list_pengajuan_underwritingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_list_pengajuan_underwritingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_list_dokumen_pengajuanCompletedEventHandler(object sender, get_list_dokumen_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_list_dokumen_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_list_dokumen_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_data_detail_pengajuanCompletedEventHandler(object sender, get_data_detail_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_data_detail_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_data_detail_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_ddl_list_bankCompletedEventHandler(object sender, get_ddl_list_bankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_ddl_list_bankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_ddl_list_bankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_ddl_list_jenis_dokumen_pengajuanCompletedEventHandler(object sender, get_ddl_list_jenis_dokumen_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_ddl_list_jenis_dokumen_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_ddl_list_jenis_dokumen_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_ddl_polis_login_useridCompletedEventHandler(object sender, get_ddl_polis_login_useridCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_ddl_polis_login_useridCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_ddl_polis_login_useridCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_userid_infoCompletedEventHandler(object sender, get_userid_infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_userid_infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_userid_infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_ddl_list_premium_typeCompletedEventHandler(object sender, get_ddl_list_premium_typeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_ddl_list_premium_typeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_ddl_list_premium_typeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void get_news_typeCompletedEventHandler(object sender, get_news_typeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_news_typeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_news_typeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void validate_userpassCompletedEventHandler(object sender, validate_userpassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validate_userpassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validate_userpassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ins_dokumen_pengajuanCompletedEventHandler(object sender, ins_dokumen_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ins_dokumen_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ins_dokumen_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void updt_statusCompletedEventHandler(object sender, updt_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updt_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updt_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void del_dokumen_pengajuanCompletedEventHandler(object sender, del_dokumen_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class del_dokumen_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal del_dokumen_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ins_pengajuanCompletedEventHandler(object sender, ins_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ins_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ins_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void upd_pengajuanCompletedEventHandler(object sender, upd_pengajuanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class upd_pengajuanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal upd_pengajuanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591